"use strict";
let lname;
lname = 'Beato';
//lname = 10;
let newName = lname.toUpperCase();
console.log(newName);
let age;
age = 27;
//age = "27";
let dob = "27";
let result = parseInt(dob);
console.log(result);
let isValid = false;
console.log(isValid);
let empList;
empList = ["Maisy", "Maisy1", "Maisy2"];
let numList;
numList = [1, 2, 3, 4, 5];
let results = numList.filter((num) => num > 2);
console.log(results);
let num = numList.find((num) => num === 2);
console.log(num);
